### ISSUE TITLE
Prompts generate unique scriptID and inputID faliure

### ISSUE THREAD

**Issue by haunthy** [predictive-technology-laboratory/sensus#174] opened 2016-06-07 16:17 UTC
1. Different prompts have the same scriptID in json files, and the ID is a constant one:
   (1)Random prompt: 
     scriptID: 420da32e-3ac9-4a31-8e58-b51142a33584
   (2)Fixed Time prompt (End of Day):
     scriptID: bdb89c5a-b45c-4b8d-ac8c-250d4fd90630

2. Different questions inside one survey have the same input ID and the ID is a constant one: 
  (1) demonicsalmon
       AfterCallPrompt(2 of them): ef3ab224-2981-4599-99e5-f1e14d7981b9
       EndOfDayPrompt(5 of them): c0bfe968-40ed-4c8e-a299-4c5696420d38
  (2) salmon:
       RandomTimePrompt (2 of them): 08a06aba-77e2-4637-b9c4-74cd606d9cad
       EndOfDayPrompt (2 of them): db826284-2948-4dfd-a6fa-9c24ae8ad01d

3. Duplicate json files generated
    This happens sometimes: the same prompt has two same json files uploaded to the cloud with different file names.

**Comment by MatthewGerber** [comment] 2016-06-07 16:31
1 and 2 are by design. Script IDs and input IDs never change. Take a look at the RunId. This is what changes between runs of a script.

As for 3, sometimes this happens and we can't control it. You should filter all data by the Datum.Id field to remove duplicate data. The SensusR package does this for you.

**Comment by haunthy** [comment] 2016-06-07 16:38
For 1, ScriptIDs should be different for different uploaded prompts. For example, Survey1 and Survey2 are both EndOfDay surveys, theoretically they should have different scriptIDs, but sometimes they happen to have the same script ID. 

 InputIDs are indeed the same 'set' for the same type of survey, but for different questions inside the survey, their input IDs should be different. But in the data uploaded, inside the same survey, 5 of the different questions have the same input ID while the rest have different input IDs

**Comment by MatthewGerber** [comment] 2016-06-07 16:43
Within Sensus, edit the protocol, go to Probes, select Scripted Interactions, and tap Share Definition. Send me the file via personal email so we can look at it.

**Comment by MatthewGerber** [comment] 2016-06-07 18:06
Closing this for now.

**Closed by MatthewGerber** 2016-06-07 18:06 UTC

**Comment by MatthewGerber** [comment] 2016-06-08 01:29
Fixed with https://github.com/predictive-technology-laboratory/sensus/commit/76e1bb629c91f21f399914393f20363b0b2f508e.
