### ISSUE TITLE
Bringing Sensus back to foreground cannot turn on MS band

### ISSUE THREAD

**Issue by haunthy** [predictive-technology-laboratory/sensus#259] opened 2016-10-13 19:56 UTC
After connecting the band with Sensus (Apple Store 12.x.x version), once it loses connection (out of bluetooth range) and came back, bringing Sensus back to foreground cannot turn the band on (though bluetooth connection already resumed).

Here're the steps how to reproduce this problem(Assume you have already paired up the band with your phone and keep your bluetooth on all the time):
1. start your band testing protocol (make sure at least the heart rate band probe is on), then you should see the green light of the band is on all the time (continuously).
2. Take your band away from your phone until the green light is off (out of the bluetooth range)
3. take your band close to your phone again --- the light should be off still
4. bring Sensus back to the foreground --- this cannot turn on the band (green light is still off)
5. However, if you restart your protocol, the band will be turned on again.

**Comment by haunthy** [comment] 2016-10-13 20:31
More update: restarting Sensus protocol can turn on the band again.

**Comment by MatthewGerber** [comment] 2016-10-13 20:47
* What version of Sensus are you running?

* Please stop by Tuesday @ 2pm if possible to demonstrate the behavior. Of,
if possible, show the behavior to Mark before then (preferred).

* Can you please send me the protocol file via email?

**Comment by haunthy** [comment] 2016-10-13 20:51
The version is the "bughunting" branch in Wes' repo --- also the one all participants are using now. 
You can get this app through this link now: https://i.diawi.com/TBpTr9
Or get it from Wes' repo.

Yea I just showed Mark the behavior in my office. And no problem I will be there on Tuesday.

Will send you the protocol that works with this bughunting version.

**Comment by MatthewGerber** [comment] 2016-10-13 20:54
Please use what's in the stores (12.*.*) to demonstrate the behavior. We
should always be testing the most current version.

**Comment by haunthy** [comment] 2016-10-14 19:01
This problem is observed on ios10. 

According to microsoft support,  they indeed have received reports that band 2 cannot talk to the background with ios10...But they cannot provide more explanation for that so far. They said the team is working on that, and there should be an update of SDK sometime -- but no promise when that can happen.

Due to some other complaints about ios bluetooth background advertising, it seems there're bugs in ios too.  At least so far, we don't have a certain answer if this is due to the band SDK or ios or both.

**Comment by MatthewGerber** [comment] 2016-10-17 03:04
@mrucker did you notice the deprecation on `UiLocalNotification` in iOS 10?

https://developer.apple.com/reference/uikit/uilocalnotification

I'm seeing issues with undelivered `UILocalNotifications`, and this might be the cause. Failed deliveries would also explain this issue. Looking into this now.

**Comment by MatthewGerber** [comment] 2016-10-17 04:05
Need to use the following with iOS 10:

https://developer.apple.com/reference/usernotifications/unusernotificationcenter

I'm starting this now, and I'll push a branch for further work.

**Comment by MatthewGerber** [comment] 2016-10-17 04:09
Started a branch for this:

https://github.com/predictive-technology-laboratory/sensus/tree/ios10-notifications

Lots of work to do.

**Comment by mrucker** [comment] 2016-10-17 04:20
Just saw it. I don't think that is the specific cause for this error though which means we can leave that work until later if you'd like :). [Here's](https://github.com/mariokorte/GoodNight/commit/b59dbde163c34b42d70a703f322173d3698b12c9) what I found, if you trust a random commit on github.

My vote would be we get unit tests and XTC going before we rework how Notifications work for iOS? Or do you think the undelivered notifications is bigger than this bug? I'm not sure what other issues you are looking at.

**Comment by MatthewGerber** [comment] 2016-10-17 04:31
I'm running the current version of develop in the debugger using the iOS 10 iPhone, and the UILocalNotifications are not being delivered for the MS Band health test. This is why the Band is not being reconnected after foregrounding Sensus. If you can figure out how to get these UILocalNotifications working again on iOS 10, that's fine, but your recent commit regarding alert titles doesn't appear to fix this. My initial test of the new notification center indicates that it works as desired.

If it's true that UILocalNotifications are not being delivered on iOS 10, then we have a significant problem that extends beyond the Band.

**Comment by mrucker** [comment] 2016-10-17 14:37
Got it. What have you done on this? If we code just for iOS10 won't we also
break old users?

Give me a day and I should be able to pull out all the notification code
into interfaces. Then we can handle notifications differently in different
iOS versions.

Would that fix the band issue too? Or are band notifications handle
separately from other notifications?

**Comment by MatthewGerber** [comment] 2016-10-17 18:03
@mrucker @wesbonelli I'm pretty sure I see what's happening here. I'm going to do some testing/dev work this afternoon. I'll email you later, and you can wrap things up, add unit tests, etc.

**Comment by MatthewGerber** [comment] 2016-10-27 03:00
This be fixed in the upcoming 13.0.0 release.

**Closed by MatthewGerber** 2016-10-27 03:00 UTC
