### ISSUE TITLE
Installing protocol makes iPhone frozen on ios 10.1

### ISSUE THREAD

**Issue by haunthy** [predictive-technology-laboratory/sensus#285] opened 2016-11-10 22:38 UTC
So far we have observed, on ios10.1+iphone6, installing the protocol will freeze the phone, but it will work after restarting the phone.

**Comment by MatthewGerber** [comment] 2016-11-10 22:54
Can you send the protocol? Does this happen all the time?

**Comment by haunthy** [comment] 2016-11-11 01:37
For Sensus 13.0, we have observed it on two iPhone6 with iOS 10.1. Not on any other model or OS yet. And for those two iPhone6, it worked after restarting the phone.

I have sent the protocol to you.

**Comment by MatthewGerber** [comment] 2016-11-18 05:00
I can't reproduce this using an iPhone 6 simulator running iOS 10.1. Can you provide any other information?

**Comment by haunthy** [comment] 2016-11-18 18:45
Sorry I only got the report from the participants once when it happened at the same time to 2 participants. Both of them use iOS 10.1 + iPhone6... And I didn't succeed to reproduce it either... Maybe we can just leave this issue here until we have more observations.

**Comment by MatthewGerber** [comment] 2016-11-18 19:00
I'm going to close this, but feel free to reopen it later if it happens.

**Closed by MatthewGerber** 2016-11-18 19:00 UTC
