### ISSUE TITLE
Add Google's Activity Recognition API

### ISSUE THREAD

**Issue by cadancai** [predictive-technology-laboratory/sensus#239] opened 2016-09-11 16:50 UTC
Answer the following questions depending on the type of issue you are submitting.
# For All Issues
### Which operating system(s) does this issue involve (Android, iOS, or both)?
# For Enhancement Issues
### What would you like Sensus to do that it does not already do?
# For Bug Report Issues

**Comment by MatthewGerber** [comment] 2016-10-27 03:02
Duplicate of #120.

**Closed** 2017-06-29 19:56 UTC
