### ISSUE TITLE
Device ID are different for ScriptDatum and ScriptRunDatum

### ISSUE THREAD

**Issue by haunthy** [predictive-technology-laboratory/sensus#221] opened 2016-08-03 20:05 UTC
For both iOS and Android,

ScriptDatum and ScriptRunDatum record different deviceIDs for the same phone.

**Comment by MatthewGerber** [comment] 2016-08-03 20:07
Can you reproduce this? If so, how? Does it always happen?

**Comment by haunthy** [comment] 2016-08-03 20:09
This happens all the time. iOS has a much longer deviceID format than Android.

**Comment by MatthewGerber** [comment] 2016-08-03 20:14
Can you reproduce this using a fresh protocol and a single device?

**Comment by haunthy** [comment] 2016-08-03 20:58
We figured out it is because, in the protocol, hash the device ID generate an anonymized deviceID (as the longer one in ScriptDatum and every other probes). Since for ScriptRunDatum, there's no option in the protocol to set anonymized, it records the real deviceID.

**Comment by wesbonelli** [comment] 2016-08-04 20:48
@MatthewGerber We're pretty confident @haunthy's explanation is the case. We looked at other data types and ScriptRun data is the only one with a different and much shorter device ID, implying ScriptRun's is the real one and the others have been hashed.

Applying any Script anonymization settings to the corresponding fields in ScriptRun seems like the behavior we want. I've been looking for where anonymization is applied to datum properties without luck. Could you point me in the right direction if that sounds good?

**Comment by MatthewGerber** [comment] 2016-08-04 20:52
That will be difficult to achieve due to the way anonymization is done.
Take a look at the AnonymizedJsonContractResolver, which is used to
serialize Datum objects to JSON.

Matt

**Comment by MatthewGerber** [comment] 2016-08-05 02:14
Closing this. Open a new issue for the anonymization of `ScriptRunDatum` if needed.

**Closed by MatthewGerber** 2016-08-05 02:14 UTC
