### ISSUE TITLE
Conditional display doesn't work

### ISSUE THREAD

**Issue by haunthy** [predictive-technology-laboratory/sensus#286] opened 2016-11-11 01:40 UTC
Conditional display doesn't work on Sensus 13.0.

**Comment by MatthewGerber** [comment] 2016-11-11 01:49
Can you send me the protocol? Thanks.

**Comment by MatthewGerber** [comment] 2016-11-12 16:19
@mrucker When we switched to the copy constructor for the `InputGroup` class it broke this feature. The problem is that `InputGroup.Copy` copies each `Input` one at a time via `Input.Copy`, which uses serialization/deserialization. This breaks the reference between the `Input`s `InputDisplayCondition.Input` objects and the `Input` objects that the `InputGroup` is obtaining via `Input.Copy`. Really convoluted, but I'm pretty sure this is the problem. Can you fix it? I'll forward you a protocol that has this problem.

**Comment by mrucker** [comment] 2016-11-12 22:31
Dr. Gerber,

Are you sure on this? 

When I first wrote the copy constructor I didn't break the references of the Inputs. This caused lots of strange problems with surveys like slider bars not working and other shenanigans. So I went back and changed it so the references are broken. Looking at how the Copy method used to work for this guy I'm fairly sure this is the right call... Am I reading this wrong? Perhaps the problem is not assigning a new Guid Id to the inputs? I looked at the Input copy method and it doesn't assign new Id's after copying. Does that make sense? I'm happy to look into the bug more just let me know.

From commit 76e1bb629c91f21f399914393f20363b0b2f508e. The last commit to modify copy before the copy constructor.
![image](https://cloud.githubusercontent.com/assets/966578/20242480/5b873dc4-a8fd-11e6-8bd5-74848d12e590.png)

Thanks

**Comment by MatthewGerber** [comment] 2016-11-13 12:49
I'm not exactly sure when the problem was introduced, but I'm pretty
confident that what I described is the cause.

**Comment by mrucker** [comment] 2016-11-13 13:52
Cool,

Good to know. Thanks for the direction. I'll dig in more today and bounce
what I find off you again since you still understand the system more than I
do.

**Comment by MatthewGerber** [comment] 2016-11-13 14:24
A bit more detail:. The ids on inputs and input groups should never be
changed since they're used to recover the structure of the survey after it
is saved locally and remotely. I think the fix here is to use the input ids
to reconnect (assign) the display condition inputs to the correct copied
inputs within the input group.

**Comment by mrucker** [comment] 2016-11-13 19:14
My computer just died... This is the second one this week.

A virus must be in one of my repos or something though if two of my
computers bit the dust. I'm not sure what I'm going to do...

Do we have a timetable on this? I'd like to go home and get my windows disk
so I can format and reinstall. However that will take me away from the mac
which is currently my only working machine that I can develop on. You
probably won't get this immediately. Just let me know when you get a chance.

**Comment by MatthewGerber** [comment] 2016-11-13 19:27
Yu is the only one waiting for this. You could ask her about her timeline.

**Comment by mrucker** [comment] 2016-11-20 03:48
Alright,

After my week long adventure in broken computer land I'm now getting caught back up.

I just committed five new unit tests to make sure the copy constructor is working like we expect in every way. GroupId's are always correct. the Input.Id is being maintained even though I'm not explicitly setting it. The reference address is being broken, but we already knew that.

Tomorrow I'll start digging into the actual bug that started this whole thread.

Thanks

**Comment by MatthewGerber** [comment] 2016-11-20 12:42
Just to be clear, if you didn't change anything other than the tests, and
the unit tests are passing, then I'd be surprised if the test is correct.
Maybe you already have this in mind based on your comment about references.
It might be worth hopping on the phone or Skype tomorrow. I can point you
to the place I saw a problem and maybe save you some time. If you already
see the problem, that's great no need to talk.

On Nov 19, 2016 10:48 PM, "Mark Rucker" <notifications@github.com> wrote:

Alright,

After my week long adventure in broken computer land I'm now getting caught
back up.

I just committed five new unit tests to make sure the copy constructor is
working like we expect in every way. GroupId's are always correct. the
Input.Id is being maintained even though I'm not explicitly setting it. The
reference address is being broken, but we already knew that.

Tomorrow I'll start digging into the actual bug that started this whole
thread.

Thanks

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/predictive-technology-laboratory/sensus/issues/286#issuecomment-261757086>,
or mute the thread

**Comment by mrucker** [comment] 2016-11-20 15:44
Yeah we can hop on a call or something today. I was going to investigate the break this afternoon.

I added the unit tests just for the copy function. The actual functionality that is broken isn't captured in these tests, so they shouldn't fail. I just wanted these in place before I started working in case I accidentally change some other piece of the copy function without realizing it. 

Now that we have a good architecture for tests you'll find I always write them before I start working just to be safe -- assuming tests aren't already in place for whatever we're working on.

**Comment by MatthewGerber** [comment] 2016-11-20 15:57
The copy function is what I'm pretty sure is broken, and that's what is
causing this bug. What time works tomorrow?

**Comment by mrucker** [comment] 2016-11-20 19:14
Oh I see your time stamp now. Man, I need to do a better job of checking message times given our non-traditional work hours. If we're going to talk tomorrow can I just stop by your office sometime? Here's my availability. 

![image](https://cloud.githubusercontent.com/assets/966578/20465439/0fb6ad24-af2b-11e6-854f-ec136dbd531b.png)

I've looked into this and think I see what you are seeing. I agree that changing the copy function would fix this problem. That wouldn't be my preferred course of action though. If you feel strongly about proceeding that way I think it might be better for you to make the changes. Given the number of pieces that rely on inputs and my current level of Sensus experience, I don't think I'd know everything I should test.

My preferred approach is to leave the copy function as is and change the relationship between Input and InputDisplayCondition. With minimal effort I think we can remove the circular reference between those two and remove the requirement that Input reference doesn't change. Both changes that, in my opinion, will make for a code base that is less likely to break with future changes and be less likely to introduce unintended bugs this time.

Thoughts?

**Comment by MatthewGerber** [comment] 2016-11-20 19:25
You can PR an alternative approach if you'd like. Hard to judge my
preference without seeing that. Or we can talk over the approach first
tomorrow.

**Comment by mrucker** [comment] 2016-11-20 20:47
We can talk tomorrow. Time?

**Closed** 2016-11-21 16:22 UTC
Labels: android, bug, ios
